import datetime as dt

from commons.config import ROOT
from commons.registry import LoadResult, TABLE_DOCS, SOURCES

# register_table() is called as an import-time side effect in each staging module (and
# in marts). docs_gen must be able to produce the FULL dictionary regardless of which
# entry point imported it first (run.py imports all sources; refresh.py imports only
# src_c/src_d) - so import every module that registers a table here, purely for that
# side effect. Do not use these names directly.
from commons import marts  # noqa: F401 - register_table side effects
from commons.staging import (  # noqa: F401 - register_table side effects
    src_a, src_b, src_c, src_d, src_e, src_f, src_g, src_h,
)

PREAMBLE = """# Data Dictionary - SD Homelessness Data Commons

Auto-generated by the pipeline. Do not edit by hand.

**Read this first:** every table here is a *signal with known biases*, not a census.
Complaint (311) and enforcement tables measure reporting and enforcement activity -
they are NOT counts of people experiencing homelessness and must never be presented
as such. Each table's **Known bias** section is part of the data.
"""


def write_data_dictionary(con, path=ROOT / "DATA_DICTIONARY.md") -> LoadResult:
    lines = [PREAMBLE, f"_Generated {dt.datetime.now():%Y-%m-%d %H:%M}_\n", "## Sources\n"]
    for sid, s in SOURCES.items():
        st = con.execute("SELECT load_status FROM meta_sources WHERE source_id=?", [sid]).fetchone()
        lines += [f"### `{sid}` - [{s['name']}]({s['url']})\n",
                  f"- **Signal type:** {s['signal_type']}  |  **Cadence:** {s['refresh_cadence']}  |  "
                  f"**Last load:** {st[0] if st and st[0] else 'n/a'}",
                  f"- **Measures:** {s['measures']}",
                  f"- **Known bias:** {s['known_bias']}\n"]
    lines.append("\n## Tables\n")
    existing = {r[0] for r in con.execute("SELECT table_name FROM information_schema.tables").fetchall()}
    for t, doc in sorted(TABLE_DOCS.items()):
        if t not in existing:
            continue
        lines += [f"### `{t}`\n",
                  f"- **Grain:** {doc['grain']}",
                  f"- **Signal type:** {doc['signal_type']}  |  **Source:** {doc['source_id']} ({doc['source_url']})",
                  f"- **Refresh:** {doc['refresh']}",
                  f"- **Measures:** {doc['measures']}",
                  f"- **Known bias:** {doc['known_bias']}\n",
                  "| column | type |", "|---|---|"]
        cols = con.execute(
            "SELECT column_name, data_type FROM information_schema.columns WHERE table_name=? ORDER BY ordinal_position",
            [t]).fetchall()
        lines += [f"| {c} | {ty} |" for c, ty in cols]
        lines.append("")
    path.write_text("\n".join(lines))
    return LoadResult("ok", len([t for t in TABLE_DOCS if t in existing]), str(path))
